name: Preview

on: [deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/preview
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          firebase-token: "${{ secrets.FIREBASE_TOKEN }}"